name: Release (Build & Publish)
'on':
  push:
    branches:
      - master

jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install --no-optional
      - run: npx webpack --progress
      - run: cp src/style.css dist/style.css
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BLOCKLIKE_NPM_AUTOMATION }}
