name: Release (Build & Publish)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # can run manually. npm will reject same version publish

jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --no-optional
      - run: npx webpack --progress
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BLOCKLIKE_NPM_AUTOMATION }}
